"""geolocation search

Revision ID: ecc0565595c0
Revises: b050606c1614
Create Date: 2025-11-03 01:33:58.018837

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ecc0565595c0'
down_revision: Union[str, Sequence[str], None] = 'b050606c1614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis;')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'buildings',
        sa.Column(
            'geolocation',
            geoalchemy2.types.Geography(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                from_text='ST_GeogFromText',
                name='geography',
                nullable=False,
            ),
            nullable=False,
        ),
    )
    op.create_index(
        'idx_buildings_geolocation',
        'buildings',
        ['geolocation'],
        unique=False,
        postgresql_using='gist',
        if_not_exists=True,
    )

    op.drop_column('buildings', 'latitude')
    op.drop_column('buildings', 'longitude')

    op.drop_constraint(
        op.f('organization_activity_activity_id_fkey'), 'organization_activity', type_='foreignkey'
    )
    op.drop_constraint(
        op.f('organization_activity_organization_id_fkey'),
        'organization_activity',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None,
        'organization_activity',
        'organizations',
        ['organization_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        None, 'organization_activity', 'activities', ['activity_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_activity', type_='foreignkey')
    op.drop_constraint(None, 'organization_activity', type_='foreignkey')
    op.create_foreign_key(
        op.f('organization_activity_organization_id_fkey'),
        'organization_activity',
        'organizations',
        ['organization_id'],
        ['id'],
    )
    op.create_foreign_key(
        op.f('organization_activity_activity_id_fkey'),
        'organization_activity',
        'activities',
        ['activity_id'],
        ['id'],
    )
    op.add_column(
        'buildings',
        sa.Column(
            'longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        'buildings',
        sa.Column(
            'latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
    )
    op.drop_index('idx_buildings_geolocation', table_name='buildings', postgresql_using='gist')
    op.drop_column('buildings', 'geolocation')
    # ### end Alembic commands ###

    op.execute('DROP EXTENSION IF EXISTS postgis;')
