"""geolocation search

Revision ID: ecc0565595c0
Revises: b050606c1614
Create Date: 2025-11-03 01:33:58.018837

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ecc0565595c0'
down_revision: str | Sequence[str] | None = 'b050606c1614'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis;')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'buildings',
        sa.Column(
            'geolocation',
            geoalchemy2.types.Geography(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                from_text='ST_GeogFromText',
                name='geography',
                nullable=False,
            ),
            nullable=True,
        ),
    )

    # Перенос имеющихся данных о расположении зданий
    op.execute("""
        UPDATE buildings
        SET geolocation = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
        WHERE longitude IS NOT NULL AND latitude IS NOT NULL
    """)

    op.alter_column('buildings', 'geolocation', nullable=False)

    # GIST для поиска по геолокации
    op.create_index(
        'idx_buildings_geolocation',
        'buildings',
        ['geolocation'],
        unique=False,
        postgresql_using='gist',
        if_not_exists=True,
    )

    op.drop_column('buildings', 'latitude')
    op.drop_column('buildings', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'buildings',
        sa.Column(
            'longitude',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'buildings',
        sa.Column(
            'latitude',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )

    op.execute("""
        UPDATE buildings
        SET 
            longitude = ST_X(geolocation::geometry),
            latitude = ST_Y(geolocation::geometry)
        WHERE geolocation IS NOT NULL
    """)

    op.alter_column('buildings', 'longitude', nullable=False)
    op.alter_column('buildings', 'latitude', nullable=False)

    op.drop_index('idx_buildings_geolocation', table_name='buildings', postgresql_using='gist')
    op.drop_column('buildings', 'geolocation')
    # ### end Alembic commands ###
